//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WndProcLog.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WndProcLog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die public class Messages
        ///{
        ///	
        ///} ähnelt.
        /// </summary>
        internal static string Messages_cs {
            get {
                return ResourceManager.GetString("Messages.cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0;WM_NULL;;
        ///1;WM_CREATE;;
        ///2;WM_DESTROY;;
        ///3;WM_MOVE;;
        ///5;WM_SIZE;;
        ///6;WM_ACTIVATE;;
        ///7;WM_SETFOCUS;;
        ///8;WM_KILLFOCUS;;
        ///10;WM_ENABLE;;
        ///11;WM_SETREDRAW;;
        ///12;WM_SETTEXT;;
        ///13;WM_GETTEXT;;
        ///14;WM_GETTEXTLENGTH;;
        ///15;WM_PAINT;;
        ///16;WM_CLOSE;;
        ///17;WM_QUERYENDSESSION;;
        ///18;WM_QUIT;;
        ///19;WM_QUERYOPEN;;
        ///20;WM_ERASEBKGND;;
        ///21;WM_SYSCOLORCHANGE;;
        ///22;WM_ENDSESSION;;
        ///24;WM_SHOWWINDOW;;
        ///25;WM_CTLCOLOR;;
        ///26;WM_WININICHANGE;;
        ///27;WM_DEVMODECHANGE;;
        ///28;WM_ACTIVATEAPP;;
        ///29;WM_FONTCHANGE;;
        ///30;WM_TIMECHANGE;;
        ///31 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string WndMsg {
            get {
                return ResourceManager.GetString("WndMsg", resourceCulture);
            }
        }
    }
}
