; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Kritzel"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "Max"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Kritzel.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro MUI_PAGE_LICENSE "..\..\..\..\..\..\pfad\zur\lizenz\IhreLizenz.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
;var ICONS_GROUP
;!define MUI_STARTMENUPAGE_NODISABLE
;!define MUI_STARTMENUPAGE_DEFAULTFOLDER "Kritzel"
;!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
;!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
;!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
;!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
;!define MUI_FINISHPAGE_RUN "$INSTDIR\Kritzel.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "German"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "KritzelSetup.exe"
InstallDir "$PROGRAMFILES\Kritzel"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "Hauptgruppe" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "Files\Fizzler.dll"
  File "Files\Ionic.Zip.dll"
  File "Files\Kritzel.exe"
  File "Files\Kritzel.exe.config"
  File "Files\Kritzel.GLRenderer.dll"
  File "Files\Kritzel.HTTPServer.dll"
  File "Files\Kritzel.OpenGl32.dll"
  File "Files\Kritzel.PointerInputLibrary.dll"
  File "Files\MuPDFLib.dll"
  File "Files\PdfSharp-gdi.dll"
  File "Files\SharpDX.Direct2D1.dll"
  File "Files\SharpDX.dll"
  File "Files\SharpDX.DXGI.dll"
  File "Files\Svg.dll"
  File "Files\Kritzel.pck"

; Shortcuts
;  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
;  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
;  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Kritzel.lnk" "$INSTDIR\Kritzel.exe"
  CreateShortCut "$DESKTOP\Kritzel.lnk" "$INSTDIR\Kritzel.exe"
;  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

;Section -AdditionalIcons
;  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
;  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
;  !insertmacro MUI_STARTMENU_WRITE_END
;SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Kritzel.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\Kritzel.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  CreateDirectory "$INSTDIR\logs"
  CreateDirectory "$INSTDIR\config"
  CreateDirectory "$INSTDIR\tmp"
  nsExec::Exec 'icacls "$INSTDIR\logs" /GRANT *S-1-1-0:F'
  nsExec::Exec 'icacls "$INSTDIR\config" /GRANT *S-1-1-0:F'
  nsExec::Exec 'icacls "$INSTDIR\tmp" /GRANT *S-1-1-0:F'
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) wurde erfolgreich deinstalliert."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "M�chten Sie $(^Name) und alle seinen Komponenten deinstallieren?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  ;!insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\Svg.dll"
  Delete "$INSTDIR\SharpDX.DXGI.dll"
  Delete "$INSTDIR\SharpDX.dll"
  Delete "$INSTDIR\SharpDX.Direct2D1.dll"
  Delete "$INSTDIR\PdfSharp-gdi.dll"
  Delete "$INSTDIR\MuPDFLib.dll"
  Delete "$INSTDIR\Kritzel.PointerInputLibrary.dll"
  Delete "$INSTDIR\Kritzel.OpenGl32.dll"
  Delete "$INSTDIR\Kritzel.GLRenderer.dll"
  Delete "$INSTDIR\Kritzel.HTTPServer.dll"
  Delete "$INSTDIR\Kritzel.exe.config"
  Delete "$INSTDIR\Kritzel.exe"
  Delete "$INSTDIR\Ionic.Zip.dll"
  Delete "$INSTDIR\Fizzler.dll"
  Delete "$INSTDIR\Kritzel.pck"

  ;Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$DESKTOP\Kritzel.lnk"
  ;Delete "$SMPROGRAMS\$ICONS_GROUP\Kritzel.lnk"
  
  Delete "$INSTDIR\Config\config.*.ini"
  Delete "$INSTDIR\logs\KritzelLog*.htm"
  RMDir "$INSTDIR\logs"
  RMDir /r "$INSTDIR\tmp"
  RMDir "$INSTDIR\config"

  ;RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd